# Generated by Django 5.2.4 on 2025-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(default='Grade 1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
