# Generated by Django 5.2.4 on 2025-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_alter_classroom_grade_alter_classroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(default='Grade 1', max_length=50),
        ),
    ]
