# Generated by Django 5.2.4 on 2025-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0007_alter_classroom_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(default='Grade 1', max_length=50, unique=True),
        ),
    ]
