# Generated by Django 5.2.4 on 2025-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
